import { expect, test } from "@playwright/test";

test.describe("View Builder", () => {
  test("build, save, and export a custom opportunities view", async ({ page }) => {
    await page.goto("/views/opportunities");

    await expect(page.getByText("List / View Builder")).toBeVisible();
    await page.getByPlaceholder("View name").fill("Closing This Quarter - E2E");
    await page.getByPlaceholder("Description").fill("Generated by playwright");

    await page.getByRole("button", { name: "Save View" }).click();
    await expect(page.getByText("View saved")).toBeVisible();

    await page.getByRole("button", { name: "Export CSV" }).click();
  });
});
