
ALTER TABLE public.contacts
  ADD COLUMN IF NOT EXISTS contact_type text,
  ADD COLUMN IF NOT EXISTS sales_role text,
  ADD COLUMN IF NOT EXISTS goes_by text,
  ADD COLUMN IF NOT EXISTS personal_email text,
  ADD COLUMN IF NOT EXISTS additional_email text,
  ADD COLUMN IF NOT EXISTS fax text,
  ADD COLUMN IF NOT EXISTS association text,
  ADD COLUMN IF NOT EXISTS asst_email text,
  ADD COLUMN IF NOT EXISTS commission_split_total numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mc_commission text,
  ADD COLUMN IF NOT EXISTS mc_status text,
  ADD COLUMN IF NOT EXISTS mc_recruitment_stage text,
  ADD COLUMN IF NOT EXISTS mc_rating text,
  ADD COLUMN IF NOT EXISTS mc_start_date date,
  ADD COLUMN IF NOT EXISTS mc_type text,
  ADD COLUMN IF NOT EXISTS mc_recruiter boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS reports_to text,
  ADD COLUMN IF NOT EXISTS mc_management_notes text,
  ADD COLUMN IF NOT EXISTS mc_orientation_date date,
  ADD COLUMN IF NOT EXISTS mc_assigned_state text,
  ADD COLUMN IF NOT EXISTS mc_compensation_plan text,
  ADD COLUMN IF NOT EXISTS mc_comments text,
  ADD COLUMN IF NOT EXISTS contact_number text,
  ADD COLUMN IF NOT EXISTS recruiter_commission numeric,
  ADD COLUMN IF NOT EXISTS internal_search_owner text,
  ADD COLUMN IF NOT EXISTS recruited_by text,
  ADD COLUMN IF NOT EXISTS actual_from_goals numeric,
  ADD COLUMN IF NOT EXISTS quota_over_goals numeric,
  ADD COLUMN IF NOT EXISTS amount_over_quota numeric,
  ADD COLUMN IF NOT EXISTS dallas_visit_date timestamptz,
  ADD COLUMN IF NOT EXISTS agreement_notes text,
  ADD COLUMN IF NOT EXISTS commission_notes text,
  ADD COLUMN IF NOT EXISTS key_reference text,
  ADD COLUMN IF NOT EXISTS key_reference_date date,
  ADD COLUMN IF NOT EXISTS reference_notes text,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS employee_id text,
  ADD COLUMN IF NOT EXISTS home_address_street text,
  ADD COLUMN IF NOT EXISTS home_address_city text,
  ADD COLUMN IF NOT EXISTS home_address_state text,
  ADD COLUMN IF NOT EXISTS home_address_zip text,
  ADD COLUMN IF NOT EXISTS home_address_country text;
